import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/Layout";
import { ShoppingCartContextProvider } from "@/contaxt/ShoppingCartContext";

export const metadata: Metadata = {
  title: "VELOMO - Auch digital: Ihr Plus an Drogerie und mehr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body>
        <ShoppingCartContextProvider>
          <Layout>{children}</Layout>
        </ShoppingCartContextProvider>
      </body>
    </html>
  );
}
